modLoader = "javafml"
loaderVersion = "[41,)"
issueTrackerURL = "https://github.com/FireMuffin303/SlimeGolem/issues"
license = "MIT"

[[mods]]
modId = "muffins_slimegolem"
version = "${version}"
displayName = "Muffin's Slime Golem"
authors = "FireMuffin303"
description = '''
Add Slime Golem to Minecraft. A good ally for finding Slime Chunks!
'''

displayURL = "https://www.curseforge.com/minecraft/mc-mods/muffins-slime-golem"
logoFile = "icon.png"

[[dependencies.muffins_slimegolem]]
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.muffins_slimegolem]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.muffins_slimegolem]]
modId = "resourcefullib"
mandatory = true
versionRange = "[2.1.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.muffins_slimegolem]]
modId = "resourcefulconfig"
mandatory = true
versionRange = "[2.0.0,)"
ordering = "NONE"
side = "BOTH"