modLoader = "javafml"
loaderVersion = "[42,)"
issueTrackerURL = "https://github.com/FireMuffin303/SlimeGolem/issues"
license = "MIT"

[[mods]]
modId = "slimegolem"
version = "${version}"
displayName = "Muffin's Slime Golem"
authors = "FireMuffin303"
description = '''
Add Slime Golem to Minecraft. A good ally for finding Slime Chunks!
'''

displayURL = "https://modrinth.com/mod/muffins-slime-golem"
logoFile = "icon.png"

[[dependencies.slimegolem]]
modId = "forge"
mandatory = true
versionRange = "[42,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.slimegolem]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.1,)"
ordering = "NONE"
side = "BOTH"

