modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/FireMuffin303/SlimeGolem/issues"
license = "MIT"

[[mods]]
modId = "muffins_slimegolem"
version = "${version}"
displayName = "Muffin's Slime Golem"
authors = "FireMuffin303"
description = '''
Add Slime Golem to Minecraft. A good ally for finding Slime Chunks!
'''

displayURL = "https://www.curseforge.com/minecraft/mc-mods/muffins-slime-golem"
logoFile = "icon.png"

[[dependencies.muffins_slimegolem]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.muffins_slimegolem]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "muffins_slimegolem-common.mixins.json"